### PR TITLE
Fix build with bullet double precision library

### PR DESCRIPTION
**Pull request by rapsys**
This pull request should fix issue #191

### CODE REVIEW

**Comment by logzero** [comment]
I think it should be enough if you just cast the constants btScalar(0), btScalar(1) etc, would be less noisy that way.

**Comment by logzero** [comment]
Although I'd be also fine with explicit instantiation Min<btScalar>(...) etc.

**Comment by rapsys** [comment]
> Although I'd be also fine with explicit instantiation `Min<btScalar>(...)` etc.

Sorry, I am not a c++ expert, I don't see what you mean.

An example of code would be welcome.

**Comment by logzero** [comment]
Min/Max/Clamp are so called function templates expecting the same argument type. The compiler will complain if they get mixed type arguments (like float and double for example), thus the casting business.

Alternatively you can explicitly tell the compiler which type of function should be used (instantiated) by writing `Min<float>` or `Min<double>` etc and the compiler will cast the arguments accordingly if possible.

So instead of

`Min(btScalar(a), btScalar(b));`

you can write

`Min<btScalar>(a, b);`

**Comment by logzero** [comment]
I've pushed a slightly cleaner variant of the fix.

Thanks for looking into it.

**Comment by rapsys** [comment]
Thanks for the upstream integration.

**Pull request closed without merging**
