### PR TITLE
Add freebsd10, use c++11 for shared_ptr

### PR DESCRIPTION
**Pull request by monwarez**
Check if it's build on all platform first

### CODE REVIEW

**Comment by monwarez** [comment]
In CCFLAGS or CXXFLAGS ?

**Comment by monwarez** [comment]
Come on , gcc didn't find GL/gl.h

**Comment by logzero** [comment]
Here the official wording regarding flags (wanted to check it myself).

CCFLAGS
General options that are passed to the C and C++ compilers.
CFLAGS
General options that are passed to the C compiler (C only; not C++).
CXXFLAGS
General options that are passed to the C++ compiler.

**Comment by logzero** [comment]
We don't include gl.h anymore. Should probably just check whether libgl is there. Need to read up how to do that with scons.

**Comment by monwarez** [comment]
Maybe check if glew.h is present instead

**Comment by logzero** [comment]
No, we don't depend on glew.

Just remove the gl.h check. It should be possible to check for libs in scons. I've just haven't had time to read the docs, busy with other things.

**Comment by logzero** [comment]
So it seems something breaks scons header check for the travis gcc build.

**Comment by logzero** [comment]
Looking at the build log, the compiler is gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

Not sure if related but that is too old for c++11.

We need to add
# Force gcc 4.8 for c++11 support
env:
  global:
    - GCC_VERSION="4.8"

**Comment by logzero** [comment]
Wait, according to log header check worked in the commit
fix ident 	b2bf000

Whatever you changed afterwards broke it again.

**Comment by logzero** [comment]
I think I got it, python is sensitive to spaces vs tabs.
Please make sure to use spaces in the SConstruct file.

**Comment by monwarez** [comment]
You are right , I have some tab in SConstruct file

**Comment by logzero** [comment]
Lets revert SConstruct to b2bf000.

**Comment by logzero** [comment]
That looks okay so far.

Getting GCC 4.8 seems to be more complex. It has to be installed manually, sigh.

See for example here:
https://github.com/Bertram25/ValyriaTear/blob/master/.travis.yml 

I am running out of time for today. Will have a look tomorrow.

**Comment by logzero** [comment]
Your last commit
Remove all tabs(I hope) 151ac97
broke header detection again btw :P

**Comment by monwarez** [comment]
I see that but it's the only way to have at least clang working

**Comment by monwarez** [comment]
Yes , finally! Actually a better way would be to test the g++ version but it's work. (I don't know how to test the version so).

**Comment by logzero** [comment]
@monwarez could you test current master on your platform, so that we hupefully can close this one. :)

**Comment by monwarez** [comment]
You mean by sync with Vdrift/Vdrift master ?

**Comment by monwarez** [comment]
I can build the current master on FreeBSD, and I try to resolve conflict

**Comment by logzero** [comment]
If it builds, I can close/reject the pull request, no need to waste time with resolving merge conflicts.

**Comment by monwarez** [comment]
You can close it

**Pull request closed without merging**
