### PR TITLE
fix-unittest

### PR DESCRIPTION
**Pull request by isghe**
reduced unit test failure:
```
./build/vdrift -test
INFO: [-------------- RUNNING UNIT TESTS --------------]
INFO: src/cfg/config.cpp(370): 'config_include' FAILED: cfg_test_file_loaded
INFO: src/svn_sourceforge.cpp(186): 'svn_source_forge' FAILED: res.size() > 10
INFO: Results: 29 succeeded, 2 failed
INFO: [-------------- UNIT TESTS FINISHED -------------]
INFO: 
INFO: Exiting
```

config_include fails because in `data/test/test.cfg` at second line:
```
include nonexistent.cfg
```

### CODE REVIEW

**Comment by isghe** [comment]
Travis CI, fails because it has to:
```
git submodule init
git submodule update
```

to download the `rapidxml` submodule.

**Comment by logzero** [comment]
read_xml was never used. I'd rather have it removed, than adding more dependencies.

**Comment by isghe** [comment]
good, this evening I'll remove

**Comment by isghe** [comment]
removed ptree_xml.cpp read_xml, write_xml, test_xml, and src/rapidxml submodule

**Pull request merged**
